#!/bin/bash

PROTOCOL_COL="\033[1m\e[37;40m"

HTTP_COL="\e[32m"
SSH_COL="\e[33m"

ERR_COL="\e[37;41m"
RESET_COL="\033[0m\e[0m"

confirm () {
    read -r -p "${1:-Wanna Update? [y/N]} " choose
    case $choose in
        [yY][eE][sS]|[yY])
            true
            ;;
        *)
            false
            ;;
    esac
}

function gitpath {
    REMOTE=`git config --get remote.origin.url`
    MSG=""
    COL=$ERR_COL
    if [[ $REMOTE == ssh* ]]; then
        COL=$SSH_COL
        MSG="SSH"
    elif [[ $REMOTE == "http"* ]]; then
        COL=$HTTP_COL
        MSG="HTTP"
    else
        COL=$ERR_COL
        MSG="UNKNOWN"
    fi
    echo -e "$PROTOCOL_COL $MSG $RESET_COL $COL $REMOTE $RESET_COL"
}


RESP=0
confirm "Auto confirm? [y/N]" && RESP=1

for i in `find . -name '.git'`
do
    DIR=$(dirname "${i}")

    cd $DIR

    gitpath

    if [ $RESP -eq 1 ]; then
        git $*
    else
        confirm "Execute? [y/N]" && git $*
    fi

    cd - > /dev/null
done
