#!/bin/bash

# This commands lists your python virtualenvs, activate the selected one and runs an command on it

env="${PYENV_ROOT:?Please set your PYENV_ROOT env variable before running $0}"

cd "$env/versions"

# TODO: refac this to handle possible spaces in virtualenv names
envs=(`find . -maxdepth 1 -type l -exec basename {} \;`)

for i in "${!envs[@]}"; do
  printf "%s\t%s\n" "$i" "${envs[$i]}"
done

read -r -p "Environment id:" choose

env="${envs[$choose]}"

cd - >> /dev/null

printf "(%s)" "$env"

pyenv activate $env

$*

pyenv deactivate
